id = "beetle"
name = "beetle"
version = "3.0.0"
schema_version = 1
authors = ["bogosorter <luiswbarbosa@gmail.com>"]
description = "beetle syntax highlighting"


[grammars.beetle]
repository = "https://github.com/bogosorter/tree-sitter-beetle"
commit = "58935ea5b778d45bf5e0e3d7dbbe655fcef164bd"
